# Generated by Django 5.0.1 on 2024-02-04 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_usersregistry_delete_registeredusers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersregistry',
            name='reenterPassword',
        ),
    ]
