# Generated by Django 5.0.1 on 2024-02-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_usersregistry_reenterpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('mobileNo', models.CharField(max_length=15)),
                ('registerUsername', models.CharField(max_length=50)),
                ('registerPassword', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='UsersRegistry',
        ),
    ]
