# Generated by Django 5.0.1 on 2024-02-06 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_users_table_delete_usersregistry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users_Table',
            new_name='UsersRegistry',
        ),
    ]
