# Generated by Django 5.0.1 on 2024-05-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userFile',
        ),
    ]
