# Generated by Django 5.0.1 on 2024-05-01 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userapp', '0002_delete_userfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='userFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('uploaded', models.DateTimeField(auto_now_add=True)),
                ('username', models.CharField(max_length=45)),
            ],
        ),
    ]
